import { neon } from '@neondatabase/serverless';
const AUTH_BASE=process.env.NEON_AUTH_URL||'https://ep-falling-cell-arwoxg24.neonauth.c-4.us-west-2.aws.neon.tech/neondb/auth';
const attempts=new Map();
function noStore(res){res.setHeader?.('Cache-Control','no-store');res.setHeader?.('X-Content-Type-Options','nosniff');res.setHeader?.('Pragma','no-cache')}
function validEmail(v){return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(String(v||''))}
function safeTenant(v){return String(v||'').toLowerCase().replace(/[^a-z0-9_-]/g,'-').slice(0,80)}
function db(){return process.env.DATABASE_URL?neon(process.env.DATABASE_URL):null}
function clientKey(req,email){return String(req.headers?.['x-forwarded-for']||req.socket?.remoteAddress||'na').split(',')[0].trim()+'|'+email}
function limited(key){const now=Date.now(),x=attempts.get(key)||{count:0,start:now};if(now-x.start>15*60*1000){attempts.set(key,{count:1,start:now});return false}x.count++;attempts.set(key,x);return x.count>8}
function clearAttempt(key){attempts.delete(key)}
async function signIn(email,password){const ctrl=new AbortController(),timer=setTimeout(()=>ctrl.abort(),10000);try{return await fetch(AUTH_BASE+'/sign-in/email',{signal:ctrl.signal,method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json'},body:JSON.stringify({email,password})})}finally{clearTimeout(timer)}}
export default async function handler(req,res){noStore(res);if(req.method!=='POST')return res.status(405).json({error:'POST_ONLY'});const b=req.body||{},action=(req.query||{}).action||b.action||'login';if(action!=='login')return res.status(404).json({error:'NOT_FOUND'});const email=String(b.email||'').trim().toLowerCase(),password=String(b.password||''),requestedTenant=safeTenant(b.tenant);if(!validEmail(email)||password.length<8||password.length>256)return res.status(400).json({error:'AUTH_FAILED'});const key=clientKey(req,email);if(limited(key))return res.status(429).json({error:'TOO_MANY_ATTEMPTS'});try{const r=await signIn(email,password),text=await r.text();let j={};try{j=JSON.parse(text)}catch{}if(!r.ok)return res.status(401).json({error:'AUTH_FAILED'});const session=j.session||j.data?.session||{},user=j.user||j.data?.user||{},token=session.access_token||session.accessToken||j.token||j.access_token,userId=String(user?.id||'');if(!token||!userId)return res.status(401).json({error:'AUTH_FAILED'});const sql=db();if(!sql)return res.status(503).json({error:'AUTH_BACKEND_UNAVAILABLE'});let memberships=[];if(requestedTenant)memberships=await sql`SELECT tenant_id,role FROM tenant_members WHERE auth_user_id=${userId} AND tenant_id=${requestedTenant} LIMIT 1`;else memberships=await sql`SELECT tenant_id,role FROM tenant_members WHERE auth_user_id=${userId} ORDER BY created_at ASC LIMIT 10`;if(!memberships.length)return res.status(403).json({error:'ACCESS_NOT_PROVISIONED'});clearAttempt(key);return res.status(200).json({token,user:{id:userId,email:String(user.email||email),name:String(user.name||'')},workspace:{tenant:String(memberships[0].tenant_id),role:String(memberships[0].role||'member')},expiresAt:session.expires_at||session.expiresAt||null})}catch(e){return res.status(503).json({error:e?.name==='AbortError'?'AUTH_TIMEOUT':'AUTH_SERVICE_UNAVAILABLE'})}}