import { neon } from '@neondatabase/serverless';
const channels={'建設・設備':['Google検索','施工事例SEO','見積追客'],'美容・サロン':['Instagram','Googleマップ','再来店追客'],'不動産':['SEO','査定LP','追客メール'],'士業・コンサル':['専門記事SEO','相談LP','見込み客育成'],'医療・クリニック':['地域SEO','Googleマップ','予約導線'],'自動車・整備':['Google検索','車検LP','定期フォロー'],'飲食・店舗':['Googleマップ','SNS','再来店施策'],'その他':['SEO','SNS','追客']};
const GATEWAY='https://ai-gateway.vercel.sh/v1/chat/completions';
function db(){return process.env.DATABASE_URL?neon(process.env.DATABASE_URL):null}function emailOk(v){return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(String(v||''))}
function aiFallback(type,b){const company=(b.company||'御社').trim(),industry=b.industry||'その他',region=b.region||'全国',service=b.service||'サービス',goal=b.goal||'問い合わせを増やす';if(type==='diagnose')return{mode:'FALLBACK',summary:`${company}は${industry}の特性に合わせ、${region}での検索流入・問い合わせ導線・追客を一体で改善するのが優先です。`,insights:['新規流入の再現性を作る','問い合わせ導線を短くする','反応別の追客を標準化する'],nextActions:['検索テーマを10件設計','事例コンテンツを1本作成','24時間・3日・7日の追客を準備']};if(type==='plan')return{mode:'FALLBACK',strategy:`${goal}に向けて、1〜30日で基盤、31〜60日で流入、61〜90日で成約率を改善します。`,priorities:['計測とCTA整備','勝ちチャネルへ集中','追客とオファー改善']};return{mode:'FALLBACK',seoTitle:`${region}の${industry}｜${service}なら${company}`,social:[`${region}で${service}をご検討中の方へ。比較時のポイントと実績をご案内します。`,`${service}は価格だけでなく、対応範囲・実績・アフターフォローも確認しましょう。`,`まずは現状の課題整理から。${company}がご相談を承ります。`],followup:`お問い合わせありがとうございます。${service}について、ご状況に合わせた進め方をご案内します。`}}
function aiSystem(type){return `あなたはORDNIXのAI集客戦略エンジンです。日本の中小企業向けに、誇張や保証をせず、実行可能で具体的な提案を作ります。個人情報を推測しません。無差別営業や迷惑送信を推奨しません。外部公開・送信は人間の承認が必要です。必ず有効なJSONだけを返してください。タスク種別:${type}`}
function aiPrompt(type,b){return JSON.stringify({task:type,company:b.company||'',industry:b.industry||'その他',region:b.region||'全国',service:b.service||'サービス',target:b.target||'',goal:b.goal||'問い合わせを増やす',currentChannel:b.channel||'',problem:b.problem||'',instruction:type==='diagnose'?'summary, insights(3), nextActions(3) を返す':type==='plan'?'strategy, priorities(3), risks(2) を返す':'seoTitle, seoDescription, social(3), googlePost, followup を返す'})}
async function runAi(type,b){const key=process.env.AI_GATEWAY_API_KEY||process.env.VERCEL_OIDC_TOKEN,model=process.env.AI_MODEL;if(!key||!model)return{...aiFallback(type,b),ai:{enabled:false,reason:!key?'AI_GATEWAY_NOT_CONFIGURED':'AI_MODEL_NOT_CONFIGURED'}};try{const r=await fetch(GATEWAY,{method:'POST',headers:{Authorization:`Bearer ${key}`,'Content-Type':'application/json'},body:JSON.stringify({model,messages:[{role:'system',content:aiSystem(type)},{role:'user',content:aiPrompt(type,b)}],temperature:.35})});if(!r.ok)throw Error(`gateway_${r.status}`);const j=await r.json();let text=j?.choices?.[0]?.message?.content||'{}';text=text.replace(/^```json\s*/i,'').replace(/```$/,'').trim();return{...JSON.parse(text),ai:{enabled:true,model,provider:'VERCEL_AI_GATEWAY',humanApprovalRequired:true}}}catch(e){return{...aiFallback(type,b),ai:{enabled:false,reason:'AI_FALLBACK'}}}}
async function saveDiagnosis(b,result){const sql=db();if(!sql||!emailOk(b.email))return{saved:false,mode:sql?'NO_EMAIL':'NO_DATABASE'};try{const rows=await sql`INSERT INTO leads(company_name,industry,email,website,challenge,diagnosis,status,source) VALUES(${String(b.company||'御社')},${String(b.industry||'その他')},${String(b.email)},${b.website||null},${String(b.problem||'')},${JSON.stringify(result)},'new','ordnix_diagnosis') RETURNING id`;const id=rows[0]?.id;if(id)await sql`INSERT INTO lead_events(lead_id,event_type,note,metadata) VALUES(${id},'diagnosis','ORDNIX無料AI集客診断',${JSON.stringify({score:result.score,grade:result.grade,channel:b.channel||null})}::jsonb)`;return{saved:true,leadId:id}}catch(e){return{saved:false,mode:'DB_ERROR'}}}
async function createCrmLead(b,stage,score){const sql=db();if(!sql||!emailOk(b.lead?.email))return{saved:false,mode:sql?'NO_EMAIL':'NO_DATABASE'};try{const l=b.lead||{},rows=await sql`INSERT INTO leads(company_name,industry,email,website,challenge,diagnosis,status,source) VALUES(${String(l.company||'見込み客')},${String(l.industry||'その他')},${String(l.email)},${l.website||null},${String(l.challenge||'')},${JSON.stringify({score,source:'control'})},${stage.toLowerCase()},'ordnix_control') RETURNING id`;return{saved:true,leadId:rows[0]?.id}}catch(e){return{saved:false,mode:'DB_ERROR'}}}
async function saveCrmEvent(b,stage,score){const sql=db(),id=Number(b.lead?.id||b.leadId||0);if(!sql||!id)return createCrmLead(b,stage,score);try{await sql`UPDATE leads SET status=${stage.toLowerCase()} WHERE id=${id}`;await sql`INSERT INTO lead_events(lead_id,event_type,note,metadata) VALUES(${id},${String(b.event||'crm')},${'ORDNIX CRM: '+stage},${JSON.stringify({stage,score})}::jsonb)`;return{saved:true,leadId:id}}catch(e){return{saved:false,mode:'DB_ERROR'}}}
async function listCrm(){const sql=db();if(!sql)return{connected:false,leads:[],counts:{}};try{const rows=await sql`SELECT id,company_name,industry,email,website,status,source,created_at FROM leads ORDER BY created_at DESC LIMIT 100`;const counts={};for(const r of rows){const s=String(r.status||'new').toUpperCase();counts[s]=(counts[s]||0)+1}return{connected:true,leads:rows,counts}}catch(e){return{connected:false,leads:[],counts:{},error:'DB_ERROR'}}}
export default async function handler(req,res){if(req.method!=='POST')return res.status(405).json({error:'POST only'});const b=req.body||{},action=(req.query||{}).action||b.action||'',company=(b.company||'御社').trim(),industry=b.industry||'その他',region=b.region||'全国',service=b.service||'サービス',goal=b.goal||'問い合わせを増やす',c=channels[industry]||channels['その他'];
if(['ai_diagnose','ai_plan','ai_content'].includes(action))return res.status(200).json(await runAi(action.replace('ai_',''),b));
if(action==='readiness')return res.status(200).json({database:!!process.env.DATABASE_URL,aiAuth:!!(process.env.AI_GATEWAY_API_KEY||process.env.VERCEL_OIDC_TOKEN),aiModel:!!process.env.AI_MODEL,externalConnectors:false,payments:false});
if(action==='crm_list')return res.status(200).json(await listCrm());
if(action==='diagnose'){const channel=b.channel||'紹介中心',problem=b.problem||'問い合わせが少ない';let acquisition=55,conversion=55,nurture=55,content=50;if(channel==='ほぼ何もしていない'){acquisition-=30;content-=25}if(channel==='紹介中心'){acquisition-=18;content-=10}if(channel==='ホームページ'){acquisition+=5;content+=8}if(channel==='SNS'){acquisition+=8;content+=15}if(channel==='広告')acquisition+=18;if(problem==='問い合わせが少ない'){acquisition-=12;conversion-=8}if(problem==='追客できていない')nurture-=30;if(problem==='成約率が低い'){conversion-=22;nurture-=10}const clamp=x=>Math.max(20,Math.min(90,x));acquisition=clamp(acquisition);conversion=clamp(conversion);nurture=clamp(nurture);content=clamp(content);const score=Math.round(acquisition*.35+conversion*.3+nurture*.2+content*.15),weakest=[['集客力',acquisition],['問い合わせ導線',conversion],['追客力',nurture],['発信力',content]].sort((a,z)=>a[1]-z[1]);const result={score,grade:score>=75?'A':score>=60?'B':score>=45?'C':'D',breakdown:{acquisition,conversion,nurture,content},weakest:weakest.slice(0,2).map(x=>x[0]),reasons:[`${channel}中心のため、新規流入の再現性を評価`,`「${problem}」を現在の最大ボトルネックとして反映`],summary:`${company}の集客スコアは${score}/100。最大の改善余地は「${weakest[0][0]}」です。${c[0]}で流入、${c[1]}で検討材料、${c[2]}で取りこぼしを減らします。`,actions:c,nextStep:'90日集客プランを生成'};result.persistence=await saveDiagnosis(b,result);return res.status(200).json(result)}
if(action==='plan'){const phases=['基盤構築','集客拡大','成約最適化'];return res.status(200).json({goal,industry,days:90,channels:c,weeks:Array.from({length:12},(_,i)=>({week:i+1,phase:phases[Math.floor(i/4)],tasks:[`${c[0]}を運用`,`${c[1]}を改善`,`${c[2]}を最適化`],kpi:i<4?'計測基盤':i<8?'問い合わせ増加':'成約率改善'}))})}
if(action==='autopilot')return res.status(200).json({mode:'ORDNIX_AUTOPILOT',today:[{type:'CONTENT',channel:c[0],title:`${service}の獲得コンテンツ`,status:'READY_FOR_REVIEW'},{type:'CASE',channel:c[1],title:'実績・事例を生成',status:'READY_FOR_REVIEW'},{type:'FOLLOWUP',channel:c[2],title:'追客を準備',status:'READY_FOR_REVIEW'},{type:'SEO',channel:'Website',title:`${region}の検索意図を分析`,status:'READY_FOR_REVIEW'},{type:'OPTIMIZE',channel:'ORDNIX',title:goal,status:'ACTIVE'}],humanApprovalRequired:true});
if(action==='content')return res.status(200).json({status:'READY_FOR_REVIEW',assets:{seo:{title:`${region}の${industry}｜${service}なら${company}`,description:`${service}の選び方を${company}が解説。`,outline:['課題','選定ポイント','費用','事例','FAQ']},social:[`${region}で${service}をご検討中の方へ。`,`実績・対応範囲・見積を確認しましょう。`,`${company}がご相談からフォローまで対応します。`],google:`${company}では${region}で${service}のご相談を受付中です。`}});
if(action==='followup')return res.status(200).json({stage:b.stage||'new',sequence:[{day:0,subject:'AI集客診断の結果について',body:'最優先の改善項目を整理しました。'},{day:1,subject:'最初の改善ポイント',body:`まず${c[0]}と問い合わせ導線をつなぎます。`},{day:3,subject:'90日で自動化する範囲',body:`${c.join('・')}を一つの運用フローにします。`},{day:7,subject:'診断後7日チェック',body:'優先順位と実行計画を再確認します。'}],sendMode:'DRAFT_UNTIL_CHANNEL_CONNECTED',unsubscribeRequired:true});
if(action==='optimize'){const visits=+b.visits||0,leads=+b.leads||0,meetings=+b.meetings||0,contracts=+b.contracts||0;let priority=contracts?'SCALE':meetings?'OFFER':leads?'NURTURE':'TRAFFIC';return res.status(200).json({priority,action:priority==='SCALE'?'勝ちチャネルへ集中':priority==='OFFER'?'料金・導入メリットを改善':priority==='NURTURE'?'追客を改善':'流入を増やす',metrics:{visits,leads,meetings,contracts}})}
if(action==='approval'){const status=(b.action||'approve')==='approve'?'APPROVED':'REJECTED';return res.status(200).json({assetId:b.assetId||'asset',status,publishEligibility:status==='APPROVED',timestamp:new Date().toISOString()})}
if(action==='crm'){const stages={diagnosis:'NEW',opened:'ENGAGED',consultation:'MEETING',proposal:'PROPOSAL',contract:'WON',lost:'LOST'},stage=stages[b.event]||'NEW',score=+b.score||0,persistence=await saveCrmEvent(b,stage,score);return res.status(200).json({lead:{...(b.lead||{}),id:persistence.leadId||b.lead?.id,stage,priority:score>=70?'HIGH':score>=50?'MEDIUM':'NORMAL',score},persistence})}
if(action==='report')return res.status(200).json({company,summary:`今週は${+b.leads||0}件のリード、${+b.meetings||0}件の商談、${+b.contracts||0}件の契約。`});if(action==='onboarding')return res.status(200).json({company,industry,region,service,goal,status:'READY'});return res.status(400).json({error:'unknown action'})}